Repository LaFesta7/LikeFesta, pull requests merged in 2023-08, with the labels that each got.

#5 [Init] 회원가입 로그인 완료
  build.gradle
  src/main/java/com/sparta/lafesta/common/config/PasswordConfig.java
  src/main/java/com/sparta/lafesta/common/config/WebSecurityConfig.java
  src/main/java/com/sparta/lafesta/common/dto/ApiResponseDto.java
  src/main/java/com/sparta/lafesta/common/dto/LoginRequestDto.java
  src/main/java/com/sparta/lafesta/common/dto/SignupRequestDto.java
  src/main/java/com/sparta/lafesta/common/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/lafesta/common/jwt/JwtAuthenticationFilter.java
  src/main/java/com/sparta/lafesta/common/jwt/JwtAuthorizationFilter.java
  src/main/java/com/sparta/lafesta/common/jwt/JwtUtil.java
  src/main/java/com/sparta/lafesta/common/security/UserDetailsImpl.java
  src/main/java/com/sparta/lafesta/common/security/UserDetailsServiceImpl.java
  src/main/java/com/sparta/lafesta/user/entity/User.java
  src/main/java/com/sparta/lafesta/user/entity/UserRoleEnum.java
  src/main/java/com/sparta/lafesta/user/repository/UserRepository.java
Labels: init

#18 [Docs] README 작성
  README.md
Labels: documentation

#17 [Feature] 페스티벌, 리뷰, 댓글 좋아요 기능 구현
  src/main/java/com/sparta/lafesta/comment/controller/CommentController.java
  src/main/java/com/sparta/lafesta/comment/dto/CommentResponseDto.java
  src/main/java/com/sparta/lafesta/comment/entity/Comment.java
  src/main/java/com/sparta/lafesta/comment/service/CommentService.java
  src/main/java/com/sparta/lafesta/comment/service/CommentServiceImpl.java
  src/main/java/com/sparta/lafesta/festival/controller/FestivalController.java
  src/main/java/com/sparta/lafesta/festival/dto/FestivalResponseDto.java
  src/main/java/com/sparta/lafesta/festival/entity/Festival.java
  src/main/java/com/sparta/lafesta/festival/service/FestivalService.java
  src/main/java/com/sparta/lafesta/festival/service/FestivalServiceImpl.java
  src/main/java/com/sparta/lafesta/like/commentLike/entity/CommentLike.java
  src/main/java/com/sparta/lafesta/like/commentLike/repository/CommentLikeRepository.java
  src/main/java/com/sparta/lafesta/like/festivalLike/entity/FestivalLike.java
  src/main/java/com/sparta/lafesta/like/festivalLike/repository/FestivalLikeRepository.java
  src/main/java/com/sparta/lafesta/like/reviewLike/entity/ReviewLike.java
  src/main/java/com/sparta/lafesta/like/reviewLike/repository/ReviewLikeRepository.java
  src/main/java/com/sparta/lafesta/review/controller/ReviewController.java
  src/main/java/com/sparta/lafesta/review/dto/ReviewResponseDto.java
  src/main/java/com/sparta/lafesta/review/entity/Review.java
  src/main/java/com/sparta/lafesta/review/service/ReviewService.java
  src/main/java/com/sparta/lafesta/review/service/ReviewServiceImpl.java
  src/main/java/com/sparta/lafesta/user/entity/User.java
Labels: enhancement

#15 [Feature]kakao-login
  src/main/java/com/sparta/lafesta/common/controller/HomeController.java
  src/main/java/com/sparta/lafesta/social/config/SocialLoginWaitConfig.java
  src/main/java/com/sparta/lafesta/social/controller/KakaoLoginController.java
  src/main/java/com/sparta/lafesta/social/dto/KakaoLoginDto.java
  src/main/java/com/sparta/lafesta/social/service/KakaoService.java
  src/main/java/com/sparta/lafesta/user/controller/UserController.java
  src/main/java/com/sparta/lafesta/user/entity/User.java
  src/main/java/com/sparta/lafesta/user/repository/UserRepository.java
  src/main/java/com/sparta/lafesta/user/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/templates/login.html
  src/main/resources/templates/main.html
Labels: enhancement

#34 [Fix] CI 파일 수정
  .github/workflows/dev-ci.yml
  src/main/java/com/sparta/lafesta/like/commentLike/repository/CommentLikeRepository.java
  src/main/java/com/sparta/lafesta/like/festivalLike/repository/FestivalLikeRepository.java
  src/main/java/com/sparta/lafesta/like/reviewLike/repository/ReviewLikeRepository.java
Labels: bug

#31 [Feature] 알림 기능 - 이메일 알림 1차
  .github/workflows/dev-ci.yml
  src/main/java/com/sparta/lafesta/LaFestaApplication.java
  src/main/java/com/sparta/lafesta/comment/service/CommentServiceImpl.java
  src/main/java/com/sparta/lafesta/email/config/MailConfiguration.java
  src/main/java/com/sparta/lafesta/email/service/MailService.java
  src/main/java/com/sparta/lafesta/festival/repository/FestivalRepository.java
  src/main/java/com/sparta/lafesta/festival/service/FestivalService.java
  src/main/java/com/sparta/lafesta/festival/service/FestivalServiceImpl.java
  src/main/java/com/sparta/lafesta/notification/dto/FestivalReminderResponseDto.java
  src/main/java/com/sparta/lafesta/notification/service/NotificationService.java
  src/main/java/com/sparta/lafesta/review/service/ReviewServiceImpl.java
  src/main/java/com/sparta/lafesta/user/entity/User.java
  src/main/resources/application.properties
  src/main/resources/templates/notification-email.html
  src/test/java/com/sparta/lafesta/LaFestaApplicationTests.java
Labels: enhancement

#29 [Refactor] 팔로우한 시간 기록 기능 추가, 클린 코딩 참고하여 일부 수정
  src/main/java/com/sparta/lafesta/festival/entity/Festival.java
  src/main/java/com/sparta/lafesta/festival/repository/FestivalRepository.java
  src/main/java/com/sparta/lafesta/follow/controller/FollowController.java
  src/main/java/com/sparta/lafesta/follow/entity/FestivalFollow.java
  src/main/java/com/sparta/lafesta/follow/entity/UserFollow.java
  src/main/java/com/sparta/lafesta/follow/repository/FestivalFollowRepository.java
  src/main/java/com/sparta/lafesta/follow/repository/UserFollowRepository.java
  src/main/java/com/sparta/lafesta/follow/service/FollowService.java
  src/main/java/com/sparta/lafesta/user/dto/SelectUserResponseDto.java
  src/main/java/com/sparta/lafesta/user/entity/User.java
  src/main/java/com/sparta/lafesta/user/repository/UserRepository.java
Labels: enhancement

#44 [Fix & Refactor] CI 환경변수 등 코드 수정
  .github/workflows/dev-ci.yml
Labels: bug, refactor

#26 [Feature] S3 서버 연동 및 init
  .gitignore
  build.gradle
  src/main/java/com/sparta/lafesta/common/config/AmazonS3Config.java
  src/main/java/com/sparta/lafesta/common/s3/S3UploadService.java
  src/main/java/com/sparta/lafesta/common/s3/dto/FileOnS3Dto.java
  src/main/java/com/sparta/lafesta/common/s3/entity/FestivalFileOnS3.java
  src/main/java/com/sparta/lafesta/common/s3/entity/FileOnS3.java
  src/main/java/com/sparta/lafesta/common/s3/entity/ReviewFileOnS3.java
  src/main/java/com/sparta/lafesta/common/s3/entity/UserFileOnS3.java
  src/main/java/com/sparta/lafesta/common/s3/repository/FestivalFileRepository.java
  src/main/java/com/sparta/lafesta/common/s3/repository/ReviewFileRepository.java
  src/main/java/com/sparta/lafesta/common/s3/repository/UserFileRepository.java
  src/main/java/com/sparta/lafesta/festival/controller/FestivalController.java
  src/main/java/com/sparta/lafesta/festival/dto/FestivalRequestDto.java
  src/main/java/com/sparta/lafesta/festival/dto/FestivalResponseDto.java
  src/main/java/com/sparta/lafesta/festival/entity/Festival.java
  src/main/java/com/sparta/lafesta/festival/service/FestivalService.java
  src/main/java/com/sparta/lafesta/festival/service/FestivalServiceImpl.java
  src/main/java/com/sparta/lafesta/review/controller/ReviewController.java
  src/main/java/com/sparta/lafesta/review/dto/ReviewResponseDto.java
  src/main/java/com/sparta/lafesta/review/entity/Review.java
  src/main/java/com/sparta/lafesta/review/service/ReviewService.java
  src/main/java/com/sparta/lafesta/review/service/ReviewServiceImpl.java
  src/main/java/com/sparta/lafesta/user/controller/UserController.java
  src/main/java/com/sparta/lafesta/user/dto/SelectUserResponseDto.java
  src/main/java/com/sparta/lafesta/user/entity/User.java
  src/main/java/com/sparta/lafesta/user/service/UserService.java
  src/main/resources/application.properties
Labels: enhancement

#37 [Feature] 알림 기능 - 이메일 알림 (완료)
  src/main/java/com/sparta/lafesta/email/service/MailService.java
  src/main/java/com/sparta/lafesta/festival/dto/FestivalResponseDto.java
  src/main/java/com/sparta/lafesta/festival/entity/Festival.java
  src/main/java/com/sparta/lafesta/festival/repository/FestivalRepository.java
  src/main/java/com/sparta/lafesta/festival/service/FestivalService.java
  src/main/java/com/sparta/lafesta/festival/service/FestivalServiceImpl.java
  src/main/java/com/sparta/lafesta/notification/dto/FestivalReminderResponseDto.java
  src/main/java/com/sparta/lafesta/notification/dto/ReminderDto.java
  src/main/java/com/sparta/lafesta/notification/entity/FestivalReminderType.java
  src/main/java/com/sparta/lafesta/notification/service/NotificationService.java
  src/main/resources/templates/notification-email.html
Labels: enhancement

#48 [Refactor] 이메일 인증 기능 및 기타 유저서비스 개선 (완료)
  src/main/java/com/sparta/lafesta/common/controller/HomeController.java
  src/main/java/com/sparta/lafesta/common/controller/ViewController.java
  src/main/java/com/sparta/lafesta/common/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/lafesta/email/service/MailService.java
  src/main/java/com/sparta/lafesta/social/controller/KakaoLoginController.java
  src/main/java/com/sparta/lafesta/user/controller/UserController.java
  src/main/java/com/sparta/lafesta/user/dto/MailConfirmRequestDto.java
  src/main/java/com/sparta/lafesta/user/dto/SignupRequestDto.java
  src/main/java/com/sparta/lafesta/user/dto/VerificationRequestDto.java
  src/main/java/com/sparta/lafesta/user/entity/VerificationCode.java
  src/main/java/com/sparta/lafesta/user/repository/UserRepository.java
  src/main/java/com/sparta/lafesta/user/repository/VerificationCodeRepository.java
  src/main/java/com/sparta/lafesta/user/service/UserService.java
  src/main/resources/templates/authentication-email.html
  src/main/resources/templates/login.html
  src/main/resources/templates/main.html
  src/main/resources/templates/sign-up.html
Labels: enhancement, refactor

#49 [Feature] 페이징 처리 기능 추가
  src/main/java/com/sparta/lafesta/comment/controller/CommentController.java
  src/main/java/com/sparta/lafesta/comment/repository/CommentRepository.java
  src/main/java/com/sparta/lafesta/comment/service/CommentService.java
  src/main/java/com/sparta/lafesta/comment/service/CommentServiceImpl.java
  src/main/java/com/sparta/lafesta/festival/controller/FestivalController.java
  src/main/java/com/sparta/lafesta/festival/repository/FestivalRepository.java
  src/main/java/com/sparta/lafesta/festival/service/FestivalService.java
  src/main/java/com/sparta/lafesta/festival/service/FestivalServiceImpl.java
  src/main/java/com/sparta/lafesta/review/controller/ReviewController.java
  src/main/java/com/sparta/lafesta/review/repostiroy/ReviewRepository.java
  src/main/java/com/sparta/lafesta/review/service/ReviewService.java
  src/main/java/com/sparta/lafesta/review/service/ReviewServiceImpl.java
Labels: enhancement, review-required

#55 [Refactor] 클린코드 추가 내용 수정
  src/main/java/com/sparta/lafesta/admin/controller/AdminController.java
  src/main/java/com/sparta/lafesta/comment/controller/CommentController.java
  src/main/java/com/sparta/lafesta/comment/service/CommentServiceImpl.java
  src/main/java/com/sparta/lafesta/festival/dto/FestivalResponseDto.java
  src/main/java/com/sparta/lafesta/festival/service/FestivalService.java
  src/main/java/com/sparta/lafesta/festival/service/FestivalServiceImpl.java
  src/main/java/com/sparta/lafesta/festivalRequest/controller/FestivalRequestController.java
  src/main/java/com/sparta/lafesta/festivalRequest/service/FestivalRequestServiceImpl.java
  src/main/java/com/sparta/lafesta/notification/dto/ReminderDto.java
  src/main/java/com/sparta/lafesta/notification/service/NotificationService.java
  src/main/java/com/sparta/lafesta/review/dto/ReviewResponseDto.java
  src/main/java/com/sparta/lafesta/review/service/ReviewService.java
  src/main/java/com/sparta/lafesta/review/service/ReviewServiceImpl.java
Labels: refactor

#53 [Feature] 웹알림 CRUD 구현
  src/main/java/com/sparta/lafesta/festival/event/FestivalCreatedEvent.java
  src/main/java/com/sparta/lafesta/festival/event/FestivalCreatedEventListener.java
  src/main/java/com/sparta/lafesta/festival/event/FestivalCreatedEventPublisher.java
  src/main/java/com/sparta/lafesta/festival/service/FestivalServiceImpl.java
  src/main/java/com/sparta/lafesta/follow/service/FollowService.java
  src/main/java/com/sparta/lafesta/notification/controller/NotificationController.java
  src/main/java/com/sparta/lafesta/notification/dto/NotificationResponseDto.java
  src/main/java/com/sparta/lafesta/notification/dto/ReminderDto.java
  src/main/java/com/sparta/lafesta/notification/entity/Notification.java
  src/main/java/com/sparta/lafesta/notification/event/ReminderSendEmailEvent.java
  src/main/java/com/sparta/lafesta/notification/event/ReminderSendEmailEventPublisher.java
  src/main/java/com/sparta/lafesta/notification/event/ReminderSendEventListener.java
  src/main/java/com/sparta/lafesta/notification/repository/NotificationRepository.java
  src/main/java/com/sparta/lafesta/notification/service/NotificationService.java
  src/main/java/com/sparta/lafesta/review/event/ReviewCreatedEvent.java
  src/main/java/com/sparta/lafesta/review/event/ReviewCreatedEventListener.java
  src/main/java/com/sparta/lafesta/review/event/ReviewCreatedEventPublisher.java
  src/main/java/com/sparta/lafesta/review/service/ReviewServiceImpl.java
Labels: enhancement, review-required

#60 [Fix] S3 수정 오류 해결
  src/main/java/com/sparta/lafesta/festival/service/FestivalServiceImpl.java
  src/main/java/com/sparta/lafesta/review/service/ReviewServiceImpl.java
  src/main/java/com/sparta/lafesta/user/service/UserService.java
Labels: bug, review-required

#57 [Feature] 뱃지 기능 구현
  src/main/java/com/sparta/lafesta/admin/service/AdminService.java
  src/main/java/com/sparta/lafesta/admin/service/AdminServiceImpl.java
  src/main/java/com/sparta/lafesta/badge/controller/BadgeController.java
  src/main/java/com/sparta/lafesta/badge/dto/BadgeRequestDto.java
  src/main/java/com/sparta/lafesta/badge/dto/BadgeResponseDto.java
  src/main/java/com/sparta/lafesta/badge/dto/UserBadgeResponseDto.java
  src/main/java/com/sparta/lafesta/badge/entity/Badge.java
  src/main/java/com/sparta/lafesta/badge/entity/BadgeConditionEnum.java
  src/main/java/com/sparta/lafesta/badge/entity/BadgeTag.java
  src/main/java/com/sparta/lafesta/badge/entity/UserBadge.java
  src/main/java/com/sparta/lafesta/badge/event/UserBadgeCreatedEvent.java
  src/main/java/com/sparta/lafesta/badge/event/UserBadgeCreatedEventListener.java
  src/main/java/com/sparta/lafesta/badge/event/UserBadgeCreatedEventPublisher.java
  src/main/java/com/sparta/lafesta/badge/repository/BadgeRepository.java
  src/main/java/com/sparta/lafesta/badge/repository/BadgeTagRepository.java
  src/main/java/com/sparta/lafesta/badge/repository/UserBadgeRepository.java
  src/main/java/com/sparta/lafesta/badge/service/BadgeService.java
  src/main/java/com/sparta/lafesta/badge/service/BadgeServiceImpl.java
  src/main/java/com/sparta/lafesta/common/s3/dto/FileOnS3Dto.java
  src/main/java/com/sparta/lafesta/common/s3/entity/BadgeFileOnS3.java
  src/main/java/com/sparta/lafesta/common/s3/repository/BadgeFileRepository.java
  src/main/java/com/sparta/lafesta/festival/dto/FestivalResponseDto.java
  src/main/java/com/sparta/lafesta/festival/event/FestivalCreatedEventListener.java
  src/main/java/com/sparta/lafesta/review/event/ReviewCreatedEventListener.java
  src/main/java/com/sparta/lafesta/review/repostiroy/ReviewRepository.java
  src/main/java/com/sparta/lafesta/review/service/ReviewServiceImpl.java
  src/main/java/com/sparta/lafesta/tag/entity/Tag.java
  src/main/java/com/sparta/lafesta/tag/repository/TagRepository.java
  src/main/java/com/sparta/lafesta/tag/service/TagService.java
  src/main/java/com/sparta/lafesta/tag/service/TagServiceImpl.java
  src/main/java/com/sparta/lafesta/user/dto/SelectUserResponseDto.java
  src/main/java/com/sparta/lafesta/user/entity/User.java
  src/main/java/com/sparta/lafesta/user/service/UserService.java
Labels: enhancement, review-required
