Repository LaFesta7/LikeFesta, pull requests merged in 2023-09, with the labels that each got.

#67 [Feature] 랭킹 조회 구현
  src/main/java/com/sparta/lafesta/festival/controller/FestivalController.java
  src/main/java/com/sparta/lafesta/festival/repository/FestivalRepository.java
  src/main/java/com/sparta/lafesta/festival/service/FestivalService.java
  src/main/java/com/sparta/lafesta/festival/service/FestivalServiceImpl.java
  src/main/java/com/sparta/lafesta/review/controller/ReviewController.java
  src/main/java/com/sparta/lafesta/review/repostiroy/ReviewRepository.java
  src/main/java/com/sparta/lafesta/review/service/ReviewService.java
  src/main/java/com/sparta/lafesta/review/service/ReviewServiceImpl.java
  src/main/java/com/sparta/lafesta/user/controller/UserController.java
  src/main/java/com/sparta/lafesta/user/repository/UserRepository.java
  src/main/java/com/sparta/lafesta/user/service/UserService.java
Labels: review-required

#70 [Feature] 조회 기능 페이징 처리
  src/main/java/com/sparta/lafesta/admin/controller/AdminController.java
  src/main/java/com/sparta/lafesta/admin/service/AdminService.java
  src/main/java/com/sparta/lafesta/admin/service/AdminServiceImpl.java
  src/main/java/com/sparta/lafesta/badge/controller/BadgeController.java
  src/main/java/com/sparta/lafesta/badge/repository/BadgeRepository.java
  src/main/java/com/sparta/lafesta/badge/repository/UserBadgeRepository.java
  src/main/java/com/sparta/lafesta/badge/service/BadgeService.java
  src/main/java/com/sparta/lafesta/badge/service/BadgeServiceImpl.java
  src/main/java/com/sparta/lafesta/festivalRequest/repository/FestivalRequestRepository.java
  src/main/java/com/sparta/lafesta/follow/controller/FollowController.java
  src/main/java/com/sparta/lafesta/follow/repository/FestivalFollowRepository.java
  src/main/java/com/sparta/lafesta/follow/repository/UserFollowRepository.java
  src/main/java/com/sparta/lafesta/follow/service/FollowService.java
  src/main/java/com/sparta/lafesta/notification/controller/NotificationController.java
  src/main/java/com/sparta/lafesta/notification/repository/NotificationRepository.java
  src/main/java/com/sparta/lafesta/notification/service/NotificationService.java
  src/main/java/com/sparta/lafesta/tag/controller/TagController.java
  src/main/java/com/sparta/lafesta/tag/repository/FestivalTagRepository.java
  src/main/java/com/sparta/lafesta/tag/repository/TagRepository.java
  src/main/java/com/sparta/lafesta/tag/service/TagService.java
  src/main/java/com/sparta/lafesta/tag/service/TagServiceImpl.java
  src/main/java/com/sparta/lafesta/user/repository/UserRepository.java
Labels: enhancement, review-required

#68 README 2차 작성 초안
  README.md
Labels: documentation, review-required

#74 [Feature] 유저 프로필 조회, 내 정보 조회, 내 정보 수정, 유저 탈퇴 기능 구현
  src/main/java/com/sparta/lafesta/user/controller/UserController.java
  src/main/java/com/sparta/lafesta/user/dto/IntroduceRequestDto.java
  src/main/java/com/sparta/lafesta/user/dto/LoginRequestDto.java
  src/main/java/com/sparta/lafesta/user/dto/MailRequestDto.java
  src/main/java/com/sparta/lafesta/user/dto/NicknameRequestDto.java
  src/main/java/com/sparta/lafesta/user/dto/PasswordRequestDto.java
  src/main/java/com/sparta/lafesta/user/dto/SignupRequestDto.java
  src/main/java/com/sparta/lafesta/user/dto/UserInfoResponseDto.java
  src/main/java/com/sparta/lafesta/user/dto/WithdrawalRequestDto.java
  src/main/java/com/sparta/lafesta/user/entity/User.java
  src/main/java/com/sparta/lafesta/user/service/UserService.java
  src/main/resources/templates/signup.html
Labels: enhancement

#80 [CI] CI Redis 환경 변수 세팅
  .github/workflows/dev-ci.yml
  .gitignore
  src/main/resources/application.properties
Labels: ci-env

#86 [Refactor] 알림 기능 개선 - 실시간 통신 SSE 구현
  src/main/java/com/sparta/lafesta/badge/event/UserBadgeCreatedEventListener.java
  src/main/java/com/sparta/lafesta/common/controller/ViewController.java
  src/main/java/com/sparta/lafesta/common/entity/DurationFormatter.java
  src/main/java/com/sparta/lafesta/festival/event/FestivalCreatedEventListener.java
  src/main/java/com/sparta/lafesta/notification/controller/NotificationController.java
  src/main/java/com/sparta/lafesta/notification/dto/NotificationResponseDto.java
  src/main/java/com/sparta/lafesta/notification/event/ReminderSendEventListener.java
  src/main/java/com/sparta/lafesta/notification/repository/EmitterRepository.java
  src/main/java/com/sparta/lafesta/notification/service/NotificationService.java
  src/main/java/com/sparta/lafesta/review/event/ReviewCreatedEventListener.java
  src/main/resources/static/images/background/img-20.jpg
  src/main/resources/static/js/main.js
  src/main/resources/static/js/notification.js
  src/main/resources/templates/index.html
  src/main/resources/templates/notification.html
Labels: refactor, review-required

#89 [Front] 관리자 페이지 프론트 구현 및 연결
  src/main/java/com/sparta/lafesta/admin/controller/AdminController.java
  src/main/java/com/sparta/lafesta/admin/service/AdminService.java
  src/main/java/com/sparta/lafesta/admin/service/AdminServiceImpl.java
  src/main/java/com/sparta/lafesta/badge/controller/BadgeController.java
  src/main/java/com/sparta/lafesta/badge/entity/BadgeConditionEnum.java
  src/main/java/com/sparta/lafesta/common/controller/ViewController.java
  src/main/java/com/sparta/lafesta/user/dto/UserInfoResponseDto.java
  src/main/resources/static/css/admin.css
  src/main/resources/static/images/background/img-21.jpg
  src/main/resources/static/js/admin.js
  src/main/resources/static/js/main.js
  src/main/resources/templates/admin.html
  src/main/resources/templates/index.html
Labels: front, review-required

#91 [Front] 내 정보 조회 및 수정 페이지 기능 추가, 페스티벌 작성 페이지 완료
  src/main/java/com/sparta/lafesta/user/controller/UserController.java
  src/main/java/com/sparta/lafesta/user/dto/UserInfoResponseDto.java
  src/main/resources/static/css/mypage.css
  src/main/resources/static/js/festival-post.js
  src/main/resources/static/js/myedit.js
  src/main/resources/templates/festival-post.html
  src/main/resources/templates/mypage-modify.html
  src/main/resources/templates/mypage.html
Labels: front, review-required

#84 [Feature] QueryDsl적용 및 키워드 검색 기능 추가
  build.gradle
  src/main/java/com/sparta/lafesta/common/config/QuerydslConfiguration.java
  src/main/java/com/sparta/lafesta/common/jwt/JwtUtil.java
  src/main/java/com/sparta/lafesta/festival/controller/FestivalController.java
  src/main/java/com/sparta/lafesta/festival/repository/FestivalRepository.java
  src/main/java/com/sparta/lafesta/festival/repository/FestivalRepositoryCustom.java
  src/main/java/com/sparta/lafesta/festival/service/FestivalService.java
  src/main/java/com/sparta/lafesta/festival/service/FestivalServiceImpl.java
  src/main/java/com/sparta/lafesta/follow/repository/FestivalFollowRepository.java
  src/main/java/com/sparta/lafesta/follow/repository/FollowRepositoryCustom.java
  src/main/java/com/sparta/lafesta/follow/repository/UserFollowRepository.java
  src/main/java/com/sparta/lafesta/follow/service/FollowService.java
  src/main/java/com/sparta/lafesta/review/repostiroy/ReviewRepository.java
  src/main/java/com/sparta/lafesta/review/repostiroy/ReviewRepositoryCustom.java
  src/main/java/com/sparta/lafesta/review/service/ReviewServiceImpl.java
  src/main/java/com/sparta/lafesta/tag/repository/TagRepositoryCustom.java
  src/main/java/com/sparta/lafesta/tag/service/TagServiceImpl.java
  src/main/java/com/sparta/lafesta/user/entity/User.java
  src/main/java/com/sparta/lafesta/user/repository/UserRepository.java
  src/main/java/com/sparta/lafesta/user/repository/UserRepositoryCustom.java
  src/main/java/com/sparta/lafesta/user/service/UserService.java
  src/main/resources/templates/kakaomap.html
Labels: refactor, review-required

#93 [Fix] 카카오 로그인 오류 해결
  src/main/java/com/sparta/lafesta/common/jwt/JwtUtil.java
Labels: bug, review-required

#94 [Front] 유저 회원 탈퇴 및 뱃지 관련 연결
  src/main/java/com/sparta/lafesta/badge/controller/BadgeController.java
  src/main/java/com/sparta/lafesta/badge/dto/UserBadgeResponseDto.java
  src/main/java/com/sparta/lafesta/badge/service/BadgeService.java
  src/main/java/com/sparta/lafesta/badge/service/BadgeServiceImpl.java
  src/main/java/com/sparta/lafesta/common/controller/ViewController.java
  src/main/java/com/sparta/lafesta/user/controller/UserController.java
  src/main/java/com/sparta/lafesta/user/dto/SelectUserResponseDto.java
  src/main/java/com/sparta/lafesta/user/service/UserService.java
  src/main/resources/static/js/badge.js
  src/main/resources/static/js/main.js
  src/main/resources/templates/index.html
  src/main/resources/templates/my-badge.html
  src/main/resources/templates/mypage.html
  src/main/resources/templates/withdrawal.html
Labels: front, review-required

#95 [Front] 페스티벌 상세조회 및 삭제(수정은 정적페이지만 완료 연결은 추후 구현 예정)
  src/main/java/com/sparta/lafesta/common/controller/ViewController.java
  src/main/java/com/sparta/lafesta/festival/dto/FestivalResponseDto.java
  src/main/resources/static/js/festival-edit.js
  src/main/resources/static/js/festival-post.js
  src/main/resources/static/js/festival.js
  src/main/resources/static/js/main.js
  src/main/resources/static/js/post.js
  src/main/resources/templates/festival-edit.html
  src/main/resources/templates/festival-post.html
  src/main/resources/templates/festival.html
  src/main/resources/templates/index.html
  src/main/resources/templates/mypage-edit.html
Labels: front, review-required

#102 [Refactor][Front]뷰에서 페이징 처리
  src/main/java/com/sparta/lafesta/festival/controller/FestivalController.java
  src/main/java/com/sparta/lafesta/festival/service/FestivalService.java
  src/main/java/com/sparta/lafesta/festival/service/FestivalServiceImpl.java
  src/main/java/com/sparta/lafesta/follow/controller/FollowController.java
  src/main/java/com/sparta/lafesta/follow/repository/FollowRepositoryCustom.java
  src/main/java/com/sparta/lafesta/follow/service/FollowService.java
  src/main/resources/static/js/main.js
  src/main/resources/templates/index.html
  src/main/resources/templates/my-follow.html
Labels: refactor, front, review-required

#112 [Front] Admin 페이지 페이지네이션 추가
  src/main/java/com/sparta/lafesta/admin/controller/AdminController.java
  src/main/java/com/sparta/lafesta/admin/service/AdminService.java
  src/main/java/com/sparta/lafesta/admin/service/AdminServiceImpl.java
  src/main/java/com/sparta/lafesta/badge/controller/BadgeController.java
  src/main/java/com/sparta/lafesta/badge/repository/BadgeRepository.java
  src/main/java/com/sparta/lafesta/badge/repository/BadgeRepositoryCustom.java
  src/main/java/com/sparta/lafesta/badge/service/BadgeService.java
  src/main/java/com/sparta/lafesta/badge/service/BadgeServiceImpl.java
  src/main/java/com/sparta/lafesta/festivalRequest/repository/FestivalRequestRepository.java
  src/main/java/com/sparta/lafesta/tag/controller/TagController.java
  src/main/java/com/sparta/lafesta/tag/repository/TagRepository.java
  src/main/java/com/sparta/lafesta/tag/service/TagService.java
  src/main/java/com/sparta/lafesta/tag/service/TagServiceImpl.java
  src/main/java/com/sparta/lafesta/user/repository/UserRepository.java
  src/main/resources/static/js/admin.js
  src/main/resources/static/js/badge.js
  src/main/resources/static/js/main.js
  src/main/resources/templates/index.html
  src/main/resources/templates/my-badge.html
  src/main/resources/templates/my-follow.html
Labels: front, review-required

#116 [Refactor] CI/CD 환경 통일
  .github/workflows/dev-ci.yml
  .github/workflows/main-cd.yml
  .gitignore
  src/main/resources/application.properties
Labels: review-required, CD/CD-env

#111 [Front] 프론트 - 백 부가기능 연결(좋아요, 랭킹, 태그 검색, 알림 읽음, 팔로우, 프로필)
  src/main/java/com/sparta/lafesta/badge/event/UserBadgeCreatedEventListener.java
  src/main/java/com/sparta/lafesta/badge/service/BadgeServiceImpl.java
  src/main/java/com/sparta/lafesta/comment/controller/CommentController.java
  src/main/java/com/sparta/lafesta/comment/dto/CommentResponseDto.java
  src/main/java/com/sparta/lafesta/comment/service/CommentService.java
  src/main/java/com/sparta/lafesta/comment/service/CommentServiceImpl.java
  src/main/java/com/sparta/lafesta/common/config/WebSecurityConfig.java
  src/main/java/com/sparta/lafesta/common/controller/ViewController.java
  src/main/java/com/sparta/lafesta/festival/controller/FestivalController.java
  src/main/java/com/sparta/lafesta/festival/dto/FestivalResponseDto.java
  src/main/java/com/sparta/lafesta/festival/event/FestivalCreatedEventListener.java
  src/main/java/com/sparta/lafesta/festival/repository/FestivalRepository.java
  src/main/java/com/sparta/lafesta/festival/service/FestivalService.java
  src/main/java/com/sparta/lafesta/festival/service/FestivalServiceImpl.java
  src/main/java/com/sparta/lafesta/follow/controller/FollowController.java
  src/main/java/com/sparta/lafesta/follow/service/FollowService.java
  src/main/java/com/sparta/lafesta/notification/dto/NotificationResponseDto.java
  src/main/java/com/sparta/lafesta/notification/dto/ReminderDto.java
  src/main/java/com/sparta/lafesta/notification/entity/Notification.java
  src/main/java/com/sparta/lafesta/notification/event/ReminderSendEventListener.java
  src/main/java/com/sparta/lafesta/review/controller/ReviewController.java
  src/main/java/com/sparta/lafesta/review/dto/ReviewResponseDto.java
  src/main/java/com/sparta/lafesta/review/event/ReviewCreatedEventListener.java
  src/main/java/com/sparta/lafesta/review/repostiroy/ReviewRepository.java
  src/main/java/com/sparta/lafesta/review/service/ReviewService.java
  src/main/java/com/sparta/lafesta/review/service/ReviewServiceImpl.java
  src/main/java/com/sparta/lafesta/user/dto/SelectUserResponseDto.java
  src/main/resources/static/css/festival-3.css
  src/main/resources/static/js/admin.js
  src/main/resources/static/js/badge.js
  src/main/resources/static/js/festival-edit.js
  src/main/resources/static/js/festival-post.js
  src/main/resources/static/js/festival-request-edit.js
  src/main/resources/static/js/festival-request-post.js
  src/main/resources/static/js/festival-request.js
  src/main/resources/static/js/festival.js
  src/main/resources/static/js/main.js
  src/main/resources/static/js/myedit.js
  src/main/resources/static/js/notification.js
  src/main/resources/static/js/profile.js
  src/main/resources/static/js/review-edit.js
  src/main/resources/static/js/review-post.js
  src/main/resources/static/js/review.js
  src/main/resources/templates/admin.html
  src/main/resources/templates/festival.html
  src/main/resources/templates/index.html
  src/main/resources/templates/my-badge.html
  src/main/resources/templates/mypage.html
  src/main/resources/templates/profile.html
  src/main/resources/templates/signup.html
  src/main/resources/templates/withdrawal.html
Labels: front, review-required

#128 [Front] 프론트 오류 해결
  src/main/resources/static/css/festival.css
  src/main/resources/static/css/mypage.css
  src/main/resources/static/js/festival.js
  src/main/resources/static/js/main.js
  src/main/resources/static/js/review.js
  src/main/resources/templates/festival-edit.html
  src/main/resources/templates/festival-post.html
  src/main/resources/templates/festival-request-edit.html
  src/main/resources/templates/festival-request-post.html
  src/main/resources/templates/festival-request.html
  src/main/resources/templates/festival.html
  src/main/resources/templates/index.html
  src/main/resources/templates/mypage-edit.html
  src/main/resources/templates/profile.html
  src/main/resources/templates/review-edit.html
  src/main/resources/templates/review-post.html
  src/main/resources/templates/review.html
Labels: bug, front, review-required

#130 [Front] 페이징 적용 완료
  src/main/java/com/sparta/lafesta/comment/controller/CommentController.java
  src/main/java/com/sparta/lafesta/comment/repository/CommentRepository.java
  src/main/java/com/sparta/lafesta/comment/service/CommentService.java
  src/main/java/com/sparta/lafesta/comment/service/CommentServiceImpl.java
  src/main/java/com/sparta/lafesta/review/controller/ReviewController.java
  src/main/java/com/sparta/lafesta/review/repostiroy/ReviewRepository.java
  src/main/java/com/sparta/lafesta/review/service/ReviewService.java
  src/main/java/com/sparta/lafesta/review/service/ReviewServiceImpl.java
  src/main/java/com/sparta/lafesta/tag/controller/TagController.java
  src/main/java/com/sparta/lafesta/tag/repository/FestivalTagRepository.java
  src/main/java/com/sparta/lafesta/tag/repository/TagRepositoryCustom.java
  src/main/java/com/sparta/lafesta/tag/service/TagService.java
  src/main/java/com/sparta/lafesta/tag/service/TagServiceImpl.java
  src/main/resources/static/css/festival.css
  src/main/resources/static/js/festival.js
  src/main/resources/static/js/main.js
  src/main/resources/static/js/review.js
  src/main/resources/templates/festival.html
  src/main/resources/templates/index.html
  src/main/resources/templates/review.html
Labels: front, review-required

#134 [Docs] 리드미 최종 작성
  README.md
Labels: documentation

#132 [Refactor] 사용자 테스트 - 유저 피드백에 따른 리팩토링 및 에러 수정
  src/main/java/com/sparta/lafesta/badge/dto/BadgeResponseDto.java
  src/main/java/com/sparta/lafesta/comment/dto/CommentResponseDto.java
  src/main/java/com/sparta/lafesta/common/controller/ViewController.java
  src/main/java/com/sparta/lafesta/common/entity/StringFormatter.java
  src/main/java/com/sparta/lafesta/festival/controller/FestivalController.java
  src/main/java/com/sparta/lafesta/festival/dto/FestivalResponseDto.java
  src/main/java/com/sparta/lafesta/festival/service/FestivalService.java
  src/main/java/com/sparta/lafesta/festival/service/FestivalServiceImpl.java
  src/main/java/com/sparta/lafesta/festivalRequest/dto/FestivaRequestlResponseDto.java
  src/main/java/com/sparta/lafesta/notification/dto/NotificationResponseDto.java
  src/main/java/com/sparta/lafesta/notification/dto/ReminderDto.java
  src/main/java/com/sparta/lafesta/review/controller/ReviewController.java
  src/main/java/com/sparta/lafesta/review/dto/ReviewResponseDto.java
  src/main/java/com/sparta/lafesta/review/service/ReviewService.java
  src/main/java/com/sparta/lafesta/review/service/ReviewServiceImpl.java
  src/main/java/com/sparta/lafesta/tag/dto/TagResponseDto.java
  src/main/java/com/sparta/lafesta/user/controller/UserController.java
  src/main/java/com/sparta/lafesta/user/dto/SelectUserResponseDto.java
  src/main/java/com/sparta/lafesta/user/dto/UserInfoResponseDto.java
  src/main/java/com/sparta/lafesta/user/service/UserService.java
  src/main/resources/static/js/festival-edit.js
  src/main/resources/static/js/festival.js
  src/main/resources/static/js/follower.js
  src/main/resources/static/js/main.js
  src/main/resources/static/js/myedit.js
  src/main/resources/static/js/profile.js
  src/main/resources/static/js/review-edit.js
  src/main/resources/static/js/review.js
  src/main/resources/templates/kakaomap.html
  src/main/resources/templates/my-follow.html
  src/main/resources/templates/my-review.html
  src/main/resources/templates/mypage.html
  src/main/resources/templates/request-festival.html
  src/main/resources/templates/tag-list.html
Labels: bug, refactor, review-required
